config/routes.rb
Gritalo::Application.routes.draw do
  resources :raffles


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
end

app/models/raffle.rb
class Raffle
  include Mongoid::Document
  field :fb_id, type: String
  field :empresa, type: String
  field :tw, type: String
  field :product, type: String
  field :name, type: String
  field :description, type: String
  field :conditions, type: String
  field :datend, type: Date
  field :main, type: Boolean, :default => false
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
  field :provider,           :type => String
  field :uid,                :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })
  field :name, :type => String
  validates_presence_of :name
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :provider, :uid, :created_at, :updated_at

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @raffles = Raffle.all
  end
end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  # GET /raffles
  # GET /raffles.json
  def index
    @raffles = Raffle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @raffles }
    end
  end

  # GET /raffles/1
  # GET /raffles/1.json
  def show
    @raffle = Raffle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @raffle }
    end
  end

  # GET /raffles/new
  # GET /raffles/new.json
  def new
    @raffle = Raffle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @raffle }
    end
  end

  # GET /raffles/1/edit
  def edit
    @raffle = Raffle.find(params[:id])
  end

  # POST /raffles
  # POST /raffles.json
  def create
    @raffle = Raffle.new(params[:raffle])

    respond_to do |format|
      if @raffle.save
        format.html { redirect_to @raffle, notice: 'Raffle was successfully created.' }
        format.json { render json: @raffle, status: :created, location: @raffle }
      else
        format.html { render action: "new" }
        format.json { render json: @raffle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /raffles/1
  # PUT /raffles/1.json
  def update
    @raffle = Raffle.find(params[:id])

    respond_to do |format|
      if @raffle.update_attributes(params[:raffle])
        format.html { redirect_to @raffle, notice: 'Raffle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @raffle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raffles/1
  # DELETE /raffles/1.json
  def destroy
    @raffle = Raffle.find(params[:id])
    @raffle.destroy

    respond_to do |format|
      format.html { redirect_to raffles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/raffles_helper.rb
module RafflesHelper
end

app/views/home/index.html.erb
<div class="row">
	<div class="span12">
		<div class="row">
			<% @raffles.each do |raffle| %>
				<%if raffle.main %>
				<% @datend = raffle.datend %>
				<div class="main deal">
					<div class="span7">
						<%= link_to  image_tag(raffle.product) , raffle %>
					</div>
					<div class="span4">
						<h1> <%=raffle.name %></h1>
						<%= raffle.description.first(300)+"..." %>

						<div class="crono">
							<label>Se Sorteara en</label>
							 <ul id="countdown">
				                <li>
				                  <span class="days">12</span>
				                  <small>Dias</small>
				                  
				                </li>
				                <li>
				                  <span class="hours">12</span>
				                  <small>Horas</small>
				                </li>
				                <li>
				                  <span class="minutes">12</span>
				                  <small>Min</small>
				                </li>
				                <li>
				                  <span class="seconds">12</span>
				                  <small>Seg</small>
				                </li>
				              </ul>
						</div>
					</div>
					
	

						<%= link_to "Participa", raffle,:class =>"btn  btn-large btn-success ln" %>
				</div>
				<% end -%>
			<% end -%>
			<% @raffles.each do |raffle| %>
				<%if raffle.main %>
				<%else%>
					<div class="span3">
						<div class="unit">
							<div class="intt">
								<%= link_to  image_tag(raffle.product) , raffle %>
								
								
									<span><b><%=raffle.name.first(50) %></b></span>
								
									<small class= "label label-success">
										Se Sorteara el <%=raffle.datend%>
									</small>
								</div>
							
						</div>
					</div>
					
				<% end -%> 
			<% end %>

		</div>	
	</div>

</div>

<!-- Scrip -->

<script type="text/javascript">
    $(document).ready(function() {
    
      $("#countdown").countdown({
        date: '<%= @datend %>' , // add the countdown's end date (i.e. 3 november 2012 12:00:00)
        format: "on" // on (03:07:52) | off (3:7:52) - two_digits set to ON maintains layout consistency
      },
      function() { 
        alert("done!") 
      });
    });
  </script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
    
<div class="container">
  <div class="logo">
  <%= link_to image_tag("logo.png"),root_path%>
  </div>
  <ul class="nav">
 
  <% if user_signed_in? %>
    <%= link_to current_user.email, user_path(current_user) %>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    
  
  <% else %>
    <%= link_to "Login Facebook", user_omniauth_authorize_path(:facebook) %> |
    <%= link_to 'Login', new_user_session_path %>
    |
    <%= link_to 'Regístrate', new_user_registration_path %>
    
  <% end %>
 
  </ul>
</div>   
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gritalo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gritalo" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
     <%= render 'layouts/navigation' %>
    <div id="container" class="container">     
        <%= render 'layouts/messages' %>
      <div id="main" role="main">
        <div class="container">
           <%= yield %>
        </div>
       
      </div>
      
    </div> <!--! end of #container -->
    <footer>
        <div class="container">
          © 2013 Gritalo.co,  Todos los derechos reservados.
        </div>
    </footer>



  </body>

</html>

app/views/raffles/_form.html.erb
<%= form_for(@raffle) do |f| %>
  <% if @raffle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raffle.errors.count, "error") %> prohibited this raffle from being saved:</h2>

      <ul>
      <% @raffle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fb_id %><br />
    <%= f.text_field :fb_id %>
  </div>
  <div class="field">
    <%= f.label :empresa %><br />
    <%= f.text_field :empresa %>
  </div>
  <div class="field">
    <%= f.label :tw %><br />
    <%= f.text_field :tw %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :conditions %><br />
    <%= f.text_field :conditions %>
  </div>
  <div>
    <%= f.text_field :datend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/raffles/edit.html.erb
<h1>Editing raffle</h1>

<%= render 'form' %>

<%= link_to 'Show', @raffle %> |
<%= link_to 'Back', raffles_path %>

app/views/raffles/index.html.erb
<h1>Listing raffles</h1>

<table>
  <tr>
    <th>Fb</th>
    <th>Empresa</th>
    <th>Tw</th>
    <th>Product</th>
    <th>Name</th>
    <th>Description</th>
    <th>Conditions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @raffles.each do |raffle| %>
  <tr>
    <td><%= raffle.fb_id %></td>
    <td><%= raffle.empresa %></td>
    <td><%= raffle.tw %></td>
    <td><%= raffle.product %></td>
    <td><%= raffle.name %></td>
    <td><%= raffle.description %></td>
    <td><%= raffle.conditions %></td>
    <td><%= link_to 'Show', raffle %></td>
    <td><%= link_to 'Edit', edit_raffle_path(raffle) %></td>
    <td><%= link_to 'Destroy', raffle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Raffle', new_raffle_path %>

app/views/raffles/new.html.erb
<h1>New raffle</h1>

<%= render 'form' %>

<%= link_to 'Back', raffles_path %>

app/views/raffles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="main deal">
    <div class="span7">
      <%= image_tag @raffle.product %>
    </div>
    <div class="span4">
      <h2><%= @raffle.name %></h2>
      <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley
      </p>
      <div class="crono">

              <ul id="countdown">
                <label>Se Sorteara en</label>
                <li>
                  <span class="days">12</span>
                  <small>Dias</small>
                  
                </li>
                <li>
                  <span class="hours">12</span>
                  <small>Horas</small>
                </li>
                <li>
                  <span class="minutes">12</span>
                  <small>Min</small>
                </li>
                <li>
                  <span class="seconds">12</span>
                  <small>Seg</small>
                </li>
              </ul>
            </div>
    
    </div>
            <iframe src="https://www.facebook.com/plugins/like.php?href=<%=raffle_path(@raffle)%>"
        scrolling="no" frameborder="0"
        style="border:none; width:450px; height:80px">
    </iframe>
      <%= link_to "Participa",root_path,:class =>"btn  btn-large btn-success ln" %>
  </div>
</div>

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#home">Description</a></li>
  <li><a href="#profile">Condiciones</a></li>
</ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="home">
    <%= @raffle.description %>
  </div>
  <div class="tab-pane" id="profile">...2</div>

</div>
 
<script>
 $('#myTab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
})
</script>



<%= link_to 'Edit', edit_raffle_path(@raffle) %> |
<%= link_to 'Back', raffles_path %>


<script type="text/javascript">
    $(document).ready(function() {
    
      $("#countdown").countdown({
        date: '<%= @raffle.datend %>' , // add the countdown's end date (i.e. 3 november 2012 12:00:00)
        format: "on" // on (03:07:52) | off (3:7:52) - two_digits set to ON maintains layout consistency
      },
      function() { 
        alert("done!") 
      });
    });
  </script>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>